### ISSUE TITLE
API Documentation on Colors Parameter for Search Endpoint

### ISSUE THREAD

**Issue by ajmarkow** [bikeindex/bike_index#1753]
Hello, Is there a section where the API docs go into more detail on the syntax that the colors parameter is expecting to receive?  Try as we may we aren't getting a response using the "try it out" function, and I can't see a spot in the API docs that explains this parameter in greater depth.  Thanks! 🚲 😄

**Comment by ajmarkow** [comment]
It seems the syntax required is key "query_items%5B%5D" and then  value "c_c**olor value goes here**" for this parameter, rather than colors as documented.

**Comment by sethherr** [comment]
Oh no! This is definitely a bug. Glad you figured out a workaround, but you should just be able to pass something like `colors=black,purple`.

Fixing this in #1757

**Comment by sethherr** [comment]
#1757 is live and this is fixed!

The API docs now work (rather than giving you an error for whatever you put in). You can use `colors=purple` when making a URL. Of course, you can continue using the color code in the `query_items`, but that is more fragile, because as the docs say, it's subject to change without notice 😉.

Let me know if there is anything else you run into!
