### ISSUE TITLE
Search is broken on mobile and desktop with Chrome

### ISSUE THREAD

**Issue by josephrowe** [bikeindex/bike_index#254]
I can't easily search for a Cannondale Quick 

When I attempt to paste in the serial number there is no visual feedback that the serial number is being searched.   After I hit the blue button with the magnifying glass the result below should be

no bikes found with serial = 9602720 and brand = Cannondale

I think I found a stolen bike, and that happens often. Using your search tool on chrome  mobile or chrome windows 7 is so painful and broken.    Please fix it.   Add a submit button with the word submit or search now or "go". . Your use of the blue button with a magnifying class goes against the UI standards of most systems.   That icon means to begin a search.   

   I suggest your site have several simple text box form items.     Text box for serial number,   text box for model  , text box for state and  check boxes for color  , allow multiple colors to be selected  

or at least keep your search as it, and have a link to a simple search tool.     Much like google has their simple search as the default, and you can turn on advanced search.   Currently your default search is too advanced for most people. I know you may like your advanced search, but I dislike it as someone who has done a lot of UI testing.   

Serial numbers are horrible. They contain 1 and l    that's one and Lowercase l as in larry.   They also contain zero and letter "O" as in oscat.     Z as in zoo looks like a 2  when the paint fills in a lot of the gaps.   So the people who make bikes make it hard to even agree on the serial number if a stolen bike is found. 

It would be nice if your search tool allowed for a partial match on a segment of the serial number.  Let people search part of the serial number.  Example   1CC09602720     is on  a bike I just found.  That's what I think the serial number is.   But what if the CCzero is really CCOhhh.    I'd like to be able to search on 9602720.  One of the C's looks like a G, or it's just a paint glitch.  Who knows.

**Comment by sethherr** [comment]
If you search using the "serial" entry, it will do [homoglyph](https://en.wikipedia.org/wiki/Homoglyph) matching and show nearby serials (which is the sort of serial matching you're talking about).

Examining the current search functionality, pasting in a serial automatically sets it as a term rather than allowing you to choose "search for serial" as an option. So, as you say, it is broken and unuseable.

@moleon - I'd like to add another bar, beneath the current bar, that is only for serials. I think this would solve a number of usability issues and make searching for serials much easier (without involving significant programming or more tricky solutions).

**Comment by josephrowe** [comment]
Seth. Thank you so much. That's such an awesome addition of the tool =
"search bike descriptions"  field.

On my computer the new tool does not seem fully functional yet.  Just FYI.

**Comment by sethherr** [comment]
@josephrowe what problems are you running into?

I found an issue where it wasn't calculating the count of bikes correctly, but that should be fixed now.
