### ISSUE TITLE
Components inconsistently handled in API

### ISSUE THREAD

**Issue by appsforartists** [bikeindex/bike_index#83]
Some bikes (like [`37599`](https://bikeindex.org/api/v1/bikes/37599)) omit the components list.  Others (like [`37487`](https://bikeindex.org/api/v1/bikes/37487)) return a list, but every value is filled with `null`s.

If the values are all `null`, the API should omit them.

**Comment by sethherr** [comment]
I think it's the right decision to include things even if they have null values, since it makes parsing easier. Since the new version of the API has different responses for single bikes and searches, the search response is no longer heinously large, expanded by all the components.

The bike [`37599`](https://bikeindex.org/api/v1/bikes/37599)) has an empty array for components because it has no components.  

The bike [`37487`](https://bikeindex.org/api/v1/bikes/37487)) now has useful information in the components fields, because of the commit.

Also, I've added this to a new milestone, since it's tied in with parsing components better. When that issue is dealt with it will improve these responses.

**Comment by sethherr** [comment]
Resolved.
