### ISSUE TITLE
Refactor AmbassadorTask after_create hook

### ISSUE THREAD

**Issue by jmromer** [bikeindex/bike_index#839]
Refactor AmbassadorTask after_create hook to:
1. Not instantiate models wherever it can be avoided, and
2. Bulk insert assignments, or
3. Create assignments in a background job

**Comment by sethherr** [comment]
If it *does* take 15 seconds for 100 (as estimated in @jmromer's [comment here](https://github.com/bikeindex/bike_index/pull/835#discussion_r290010156), the after_create hook will eventually fail - because of unicorn worker killer.

I think for fault tolerance, making this a background job makes a lot of sense - in case the db is under heavy load, or something else weird happens - since with the check to make sure ambassadors aren't double assigned
