### ISSUE TITLE
Bike missing `images`, but has `thumbnail` and `photo`

### ISSUE THREAD

**Issue by appsforartists** [bikeindex/bike_index#84]
https://bikeindex.org/api/v1/bikes/37646

**Comment by sethherr** [comment]
This is because the photo is a stock photo. If you use the new API it will be clearer that bikes have stock photos.

You can check out the documentation for API v2 at [documentation/api_2](https://bikeindex.org/documentation/api_v2) and see what's up. There are upcoming features, the existing features will continue to exist though.
