### ISSUE TITLE
Refactor Time.now invocations?

### ISSUE THREAD

**Issue by jmromer** [bikeindex/bike_index#841]
I notice we use the TZ-naive `Time.now` in a lot of places in the code -- we may want to consider normalizing on `Time.current` or `Time.zone.now`.

See: https://rails-bestpractices.com/posts/2014/10/22/use-time-zone-now-instead-of-time-now/

```rb
# app/models/ambassador_task_assignment.rb L16-31 (363a2f9a)

scope :pending_completion, -> { incomplete.or(where("completed_at > ?", Time.now - 2.hours)) }
scope :locked_completed, -> { completed.where("completed_at < ?", Time.now - 2.hours) }
scope :task_ordered, -> { order(ambassador_task_id: :asc) }
# ...
def update_associated_user
  ambassador.update_attributes(updated_at: Time.now)
```

**Comment by sethherr** [comment]
It shouldn't matter for the examples you gave for `Time.now` - because it's in relation to the current time, regardless of the zone. And also because we aren't storing times in different zones in the database, or allowing users to change their configured timezone.

If we were using non-relative time, or displaying the time this would be relevant. There may very well be places this is relevant in the app, if so, reopen this and point it out!

Currently, for user facing things, we localize time using [moment timezone](https://momentjs.com/timezone/) - which relegates all time localization to javascript, and means we don't have to deal with timezones in ruby, other then when accepting dates/times input from users. And javascript (once again via moment) should set the users timezone in a hidden field on these forms, which means we still get to mostly ignore timezones.

There are a couple of edge cases I can think of - for example the charts in admin from chartkick - but I think we can safely ignore these for now - pending finding a major issue that affects multiple users.

**Comment by jmromer** [comment]
> pending finding a major issue that affects multiple users.

😬

**Comment by sethherr** [comment]
Yeah, phrasing there makes it sound horrific. But major issue in this case being: incorrect time.

**Comment by sethherr** [comment]
@jmromer found a place where using `Time.now` caused a bug which was fixed by using `Time.current` - https://github.com/bikeindex/bike_index/pull/887#discussion_r293558352 so I'm stopping being a curmudgeon and accepting the recommendation.
