### ISSUE TITLE
Tweet reported stolen bike when bike reported stolen. 

### ISSUE THREAD

**Issue by digitalcake** [bikeindex/bike_index#96]
I think an attempt to tweet bikes stolen at the moment users report them stolen will make the social aspect of trying to recover bikes that much more useful. I think maybe making a twitter client to send a tweet at the bike controller update or on a callback on the model when the bike is updated as stolen. 

I noticed the approved stolen attribute on the bike model. What is the context of this attribute and would that possibly be the case at which you would send a tweet?

**Comment by sethherr** [comment]
We do actually do that with the approved stolen attribute. Once it's approved, we post the bike to the https://github.com/adherr/stolen_bike_alerter which in turn tweets to the regional twitter account closest to the crime (or uses the USA account if there isn't one)

Bryan likes to review and approve the stolen listings to make sure that they're legit and that the information is entered in a way that is useful and intelligent. I'm going to ask him to weigh in on this, because I don't really deal with it :smile:

**Comment by bhance** [comment]
The approval process on stolen bikes happens because there's still a lot of BS I catch before some of these go live, things like 

a) crap descriptions or outright errors 
b) people listing FOUND bikes, motorcycles, lawnmowers, you name it. The internet is awash with idiots.
c) things like "I have security video" - but no uploaded video, etc 

All of which are cases where I follow up and make some corrections or interventions before we push a listing live. 

I would like to use the maps as a feeder for cities in which we have twitter presences though - something like "want to help us find these bikes? follow us at @stolenbikessfo" for the SF-area map, etc.

**Comment by sethherr** [comment]
Ok. Bryan further clarified:

> there's so much crap in there that gets caught and it's a good way to engage people via email

So I think we're going to continue on hand approving and close this issue.
